/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package popup;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import smart.karyawan;
import smart.restok;

/**
 *
 * @author ASUS
 */
public class returnbarang extends javax.swing.JFrame {

    /**
     * Creates new form coba
     */
    public returnbarang() {
        initComponents();
         // makeButtonTransparent(kembali);
         //  makeButtonTransparent(tambah);
           id_supplier.setOpaque(false);
        id_supplier.setBackground(new Color(0, 0, 0, 0));
        id_barang.setOpaque(false);
        id_barang.setBackground(new Color(0, 0, 0, 0));
         nama_produk.setOpaque(false);
        nama_produk.setBackground(new Color(0, 0, 0, 0));
        id_pembelian.setOpaque(false);
        id_pembelian.setBackground(new Color(0, 0, 0, 0));
         alasan.setOpaque(false);
        alasan.setBackground(new Color(0, 0, 0, 0));
        harga_jual.setOpaque(false);
          this.setBackground(new Color(0, 0, 0, 0));
        harga_jual.setBackground(new Color(0, 0, 0, 0));
          

    }
    
     private void makeButtonTransparent(JButton button) {
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
    }
    
    
    
    class Coba extends JFrame {
    public Coba() {
        setTitle("Popup Frame - Coba");
        setSize(200, 150);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        nama_produk = new javax.swing.JTextField();
        id_pembelian = new javax.swing.JTextField();
        harga_jual = new javax.swing.JTextField();
        id_supplier = new javax.swing.JTextField();
        id_barang = new javax.swing.JTextField();
        alasan = new javax.swing.JTextField();
        tgl_return = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama_produk.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nama_produk.setBorder(null);
        nama_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_produkActionPerformed(evt);
            }
        });
        getContentPane().add(nama_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 260, 30));

        id_pembelian.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        id_pembelian.setBorder(null);
        getContentPane().add(id_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 260, 40));

        harga_jual.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        harga_jual.setBorder(null);
        getContentPane().add(harga_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 260, 30));

        id_supplier.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        id_supplier.setBorder(null);
        id_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_supplierActionPerformed(evt);
            }
        });
        getContentPane().add(id_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 260, 50));

        id_barang.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        id_barang.setBorder(null);
        id_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_barangActionPerformed(evt);
            }
        });
        getContentPane().add(id_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 260, 40));

        alasan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        alasan.setBorder(null);
        getContentPane().add(alasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 300, 40));

        tgl_return.setBackground(new java.awt.Color(164, 107, 9));
        tgl_return.setForeground(new java.awt.Color(116, 77, 6));
        tgl_return.setFont(new java.awt.Font("Futura Md BT", 0, 16)); // NOI18N
        getContentPane().add(tgl_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 320, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return_barang_paling_terbaru.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_supplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_supplierActionPerformed

    private void nama_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_produkActionPerformed

    private void id_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_barangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnbarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alasan;
    private javax.swing.JTextField harga_jual;
    private javax.swing.JTextField id_barang;
    private javax.swing.JTextField id_pembelian;
    private javax.swing.JTextField id_supplier;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nama_produk;
    private com.toedter.calendar.JDateChooser tgl_return;
    // End of variables declaration//GEN-END:variables
}
