/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package popup;

import Config.koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import smart.karyawan;
import smart.restok;

/**
 *
 * @author ASUS
 */
public class ubahkaryawan extends javax.swing.JFrame {
    private ResultSet rs;

    /**
     * Creates new form coba
     */
    public ubahkaryawan() {
        initComponents();
          makeButtonTransparent(kembali);
            makeButtonTransparent(ubah);
              this.setBackground(new Color(0, 0, 0, 0));
            
        no_karyawan.setBackground(new Color(0, 0, 0, 0));
        nama_karyawan.setOpaque(false);
        nama_karyawan.setBackground(new Color(0, 0, 0, 0));
         no_telp.setOpaque(false);
        no_telp.setBackground(new Color(0, 0, 0, 0));
        password.setOpaque(false);
        password.setBackground(new Color(0, 0, 0, 0));
          RFID.setOpaque(false);
        RFID.setBackground(new Color(0, 0, 0, 0));

    }

    public ubahkaryawan(int id_karyawan, String namaKaryawan, String noTelp, String password, String role, String rfid) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
     private void makeButtonTransparent(JButton button) {
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
    }
    
    
    
    class Coba extends JFrame {
    public Coba() {
        setTitle("Popup Frame - Coba");
        setSize(200, 150);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ubah = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        nama_karyawan = new javax.swing.JTextField();
        no_telp = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        no_karyawan = new javax.swing.JTextField();
        role = new javax.swing.JComboBox<>();
        RFID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 190, 30));

        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 200, 30));

        nama_karyawan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        nama_karyawan.setBorder(null);
        getContentPane().add(nama_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 390, 40));

        no_telp.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        no_telp.setBorder(null);
        getContentPane().add(no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 390, 40));

        password.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 400, 40));

        no_karyawan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        no_karyawan.setBorder(null);
        no_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_karyawanActionPerformed(evt);
            }
        });
        getContentPane().add(no_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 390, 40));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "owner", "kasir", " " }));
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 410, 40));

        RFID.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        RFID.setBorder(null);
        getContentPane().add(RFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 400, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ubah karyawan (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
String idKaryawan = no_karyawan.getText();
String namaKaryawan = nama_karyawan.getText();
String noTelp = no_telp.getText();
String Password = password.getText();
String Role = role.getSelectedItem().toString();
String rfid = RFID.getText();

try {
    Connection conn = koneksi.getConnection();
    String sql = "UPDATE karyawan SET nama_karyawan = ?, no_telp = ?, password = ?, role = ?, rfid = ? WHERE id_karyawan = ?";
    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, namaKaryawan);
    pst.setString(2, noTelp);
    pst.setString(3, Password);
    pst.setString(4, Role);
    pst.setString(5, rfid);
    pst.setString(6, idKaryawan); // WHERE id_karyawan = ?

    int updatedRows = pst.executeUpdate();

    if (updatedRows > 0) {
         notifberhasilubhkrw popup = new notifberhasilubhkrw();
              popup.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Gagal mengubah data. ID Karyawan tidak ditemukan.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null,
            "Kesalahan: " + e.getMessage(),
            "Kesalahan Database",
            JOptionPane.ERROR_MESSAGE
    );
    e.printStackTrace();
}

    }//GEN-LAST:event_ubahActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
          new karyawan().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_kembaliActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void no_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_karyawanActionPerformed
        // TODO add your handling code here:
  String noKaryawan = no_karyawan.getText();

try {
    Connection conn = koneksi.getConnection();
    PreparedStatement pst = conn.prepareStatement("SELECT * FROM karyawan WHERE id_karyawan = ?");
    pst.setString(1, noKaryawan);
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        String namaKaryawan = rs.getString("nama_karyawan");
        String noTelp = rs.getString("no_telp");
        String Password = rs.getString("password");
        String Role = rs.getString("role");
        String rfid = rs.getString("rfid");

        nama_karyawan.setText(namaKaryawan);
        no_telp.setText(noTelp);
        password.setText(Password);
        role.setSelectedItem(Role); // JComboBox update
        RFID.setText(rfid);
    } else {
        JOptionPane.showMessageDialog(this, "No Karyawan tidak ditemukan", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        nama_karyawan.setText("");
        no_telp.setText("");
        password.setText("");
        role.setSelectedIndex(-1); // Tidak memilih apapun
        RFID.setText("");
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null,
            "Kesalahan: " + e.getMessage(),
            "Kesalahan Database",
            JOptionPane.ERROR_MESSAGE
    );
    e.printStackTrace();
}

    }//GEN-LAST:event_no_karyawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahkaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RFID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama_karyawan;
    private javax.swing.JTextField no_karyawan;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
