/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package popup;

import Config.koneksi;
import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import smart.*;

/**
 *
 * @author acer
 */
public class ubahkaryawan extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public ubahkaryawan(String idKaryawan, String namaKaryawan, String noTelp, String password1, String role1, String rfid) {
        initComponents();
        
        makeButtonTransparent(kembali);
        makeButtonTransparent(ubah);
       // customizeTable();
         nokaryawan.setOpaque(false);
        nokaryawan.setBackground(new Color(0, 0, 0, 0));
         nama.setOpaque(false);
        nama.setBackground(new Color(0, 0, 0, 0));
        nohp.setOpaque(false);
        nohp.setBackground(new Color(0, 0, 0, 0));
        password.setOpaque(false);
        password.setBackground(new Color(0, 0, 0, 0));
         RFID.setOpaque(false);
        RFID.setBackground(new Color(0, 0, 0, 0));
        
        
    }

    private ubahkaryawan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void makeButtonTransparent(JButton button) {
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nokaryawan = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        role = new javax.swing.JComboBox<>();
        RFID = new javax.swing.JTextField();
        kembali = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nokaryawan.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        nokaryawan.setForeground(new java.awt.Color(116, 77, 6));
        nokaryawan.setBorder(null);
        nokaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nokaryawan.setEnabled(false);
        nokaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nokaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(nokaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 320, 40));

        nama.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        nama.setBorder(null);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 330, 40));

        nohp.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        nohp.setBorder(null);
        getContentPane().add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 330, 40));

        password.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 330, 40));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "owner", "kasir" }));
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 410, 40));

        RFID.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        RFID.setBorder(null);
        RFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFIDActionPerformed(evt);
            }
        });
        getContentPane().add(RFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 330, 40));

        kembali.setBorder(null);
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 210, 30));

        ubah.setBorder(null);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ubah karyawan (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private String generateCode() {
    String kodeMenu = "KR001"; // Default kode pertama jika belum ada data

    try (Connection conn = koneksi.getConnection()) { // Pastikan Koneksi.getConnection() mengembalikan koneksi valid
        if (conn != null) {
            String query = "SELECT id_karyawan FROM karyawan ORDER BY id_karyawan DESC LIMIT 1";

            try (java.sql.Statement statem = conn.createStatement();
                 ResultSet resultSet = statem.executeQuery(query)) {

                if (resultSet.next()) {
                    String lastKode = resultSet.getString("id_karyawan"); // Ambil kode terakhir
                    int kodeNum = Integer.parseInt(lastKode.substring(2)) + 1; // Ambil angka setelah "KR"
                    kodeMenu = String.format("KR%03d", kodeNum); // Format KRxxx dengan leading zero
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return kodeMenu;
}
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void nokaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nokaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nokaryawanActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void RFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RFIDActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
String id_karyawan = generateCode(); // Pastikan ini adalah ID yang valid
String namaKaryawan = nama.getText();
String noTelp = nohp.getText();
String Password = password.getText();
String selectedRole = role.getSelectedItem().toString();
String Rfid = RFID.getText();

// Periksa apakah semua field sudah diisi
if (namaKaryawan.isEmpty() || noTelp.isEmpty() || selectedRole.isEmpty() || Password.isEmpty() || Rfid.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// Konfirmasi update data
int confirm = JOptionPane.showConfirmDialog(this,
        "Apakah Anda yakin ingin memperbarui data?",
        "Konfirmasi Update",
        JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    // Query untuk memperbarui data karyawan
    String query = "UPDATE karyawan SET nama_karyawan=?, no_telp=?, password=?, role=?, RFID=? WHERE id_karyawan=?";

    // Update data di database
    try (Connection conn = koneksi.getConnection(); PreparedStatement stat = conn.prepareStatement(query)) {
        // Set nilai parameter
        stat.setString(1, namaKaryawan);
        stat.setString(2, noTelp);
        stat.setString(3, Password);
        stat.setString(4, selectedRole);
        stat.setString(5, Rfid);
        stat.setString(6, id_karyawan); // Pastikan ini diaktifkan kembali

        // Eksekusi query
        int rowsAffected = stat.executeUpdate();

        // Periksa apakah data berhasil diperbarui
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
            // Buka kembali halaman karyawan
            karyawan karyawanPage = new karyawan();
            karyawanPage.setVisible(true);

            // Tutup halaman ubah karyawan
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        // Menangani kesalahan
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

    }//GEN-LAST:event_ubahActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
           new karyawan().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahkaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RFID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField nokaryawan;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
